name: Deploy on self-hosted runner

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: Run `docker compose`
      env:
        KAFKA_ADVERTISED_LISTENERS: ${{ secrets.KAFKA_ADVERTISED_LISTENERS }}
      run: docker compose -f composes/kafka.yaml -p kafka-clusters up --build -d 
  